name: easy_dialog
description: Easy Dialog package helps you easily create basic or custom dialogs.
version: 1.1.0

homepage: https://github.com/ricardonior29/easy_dialog

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


